FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN curl -s https://developer.salesforce.com/media/salesforce-cli/install.sh | bash
# Install Salesforce CLI using the new official method
RUN npm install --global
